server:
  api_prefix: /api/v1
  port: 8080
  write_timeout: 10s
  read_timeout: 10s
  max_header_bytes: 1
  idle_timeout: 60s
  allow_origins: 
    - http://localhost:3000
  allow_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin 
    - Content-Type
  expose_headers:
    - Content-Length
  allow_credentials: true
  max_age: 12h

jwt:
  access_name:
  refresh_name:
  guest_name:
  secret_key:
  access_expires_in:
  refresh_expires_in:

postgresql:
  host:
  port:
  user:
  password:
  ssl_mode:
  db_name:

rabbitmq:
  host:
  user:
  password:
  vhost:

redis:
  host:
  port:
  password:

s3:
  bucket: 
  folder:
  access_key_id: 
  secret_access_key:
  region: 

smtp:
  host: 
  port: 
  user: 
  password:

imap:
  host:
  port:
  user: 
  password:
